In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
data = {
    "Age": [22, 25, np.nan, 28, 35, np.nan, 40],
    "Salary": [25000, np.nan, 32000, 28000, np.nan, 50000, 52000],
    "Experience": [1, 3, 5, np.nan, 10, 12, np.nan]
}

df = pd.DataFrame(data)
df

    Age   Salary  Experience
0  22.0  25000.0         1.0
1  25.0      NaN         3.0
2   NaN  32000.0         5.0
3  28.0  28000.0         NaN
4  35.0      NaN        10.0
5   NaN  50000.0        12.0
6  40.0  52000.0         NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         5 non-null      float64
 1   Salary      5 non-null      float64
 2   Experience  5 non-null      float64
dtypes: float64(3)
memory usage: 300.0 bytes

In [4]:
df.isnull().sum()

Age           2
Salary        2
Experience    2
dtype: int64

In [5]:
df.describe()

             Age        Salary  Experience
count   5.000000      5.000000    5.000000
mean   30.000000  37400.000000    6.200000
std     7.382412  12680.693987    4.658326
min    22.000000  25000.000000    1.000000
25%    25.000000  28000.000000    3.000000
50%    28.000000  32000.000000    5.000000
75%    35.000000  50000.000000   10.000000
max    40.000000  52000.000000   12.000000

In [6]:
df_mean = df.fillna(df.mean())
df_mean

    Age   Salary  Experience
0  22.0  25000.0         1.0
1  25.0  37400.0         3.0
2  30.0  32000.0         5.0
3  28.0  28000.0         6.2
4  35.0  37400.0        10.0
5  30.0  50000.0        12.0
6  40.0  52000.0         6.2

In [7]:
df_median = df.fillna(df.median())
df_median

    Age   Salary  Experience
0  22.0  25000.0         1.0
1  25.0  32000.0         3.0
2  28.0  32000.0         5.0
3  28.0  28000.0         5.0
4  35.0  32000.0        10.0
5  28.0  50000.0        12.0
6  40.0  52000.0         5.0

In [8]:
df_ffill = df.fillna(method="ffill")
df_ffill

/tmp/ipython-input-1873506356.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method="ffill")

    Age   Salary  Experience
0  22.0  25000.0         1.0
1  25.0  25000.0         3.0
2  25.0  32000.0         5.0
3  28.0  28000.0         5.0
4  35.0  28000.0        10.0
5  35.0  50000.0        12.0
6  40.0  52000.0        12.0

In [9]:
imputer_mean = SimpleImputer(strategy="mean")
df_sklearn_mean = pd.DataFrame(
    imputer_mean.fit_transform(df),
    columns=df.columns
)

df_sklearn_mean

    Age   Salary  Experience
0  22.0  25000.0         1.0
1  25.0  37400.0         3.0
2  30.0  32000.0         5.0
3  28.0  28000.0         6.2
4  35.0  37400.0        10.0
5  30.0  50000.0        12.0
6  40.0  52000.0         6.2

In [10]:
imputer_median = SimpleImputer(strategy="median")

df_sklearn_median = pd.DataFrame(
    imputer_median.fit_transform(df),
    columns=df.columns
)

df_sklearn_median

    Age   Salary  Experience
0  22.0  25000.0         1.0
1  25.0  32000.0         3.0
2  28.0  32000.0         5.0
3  28.0  28000.0         5.0
4  35.0  32000.0        10.0
5  28.0  50000.0        12.0
6  40.0  52000.0         5.0